config/routes.rb
FirstApp::Application.routes.draw do

  resources :edificios

  root 'main#home'

  # Autent... routes  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/login',  to: 'sessions#login',         via: 'post' #acceso por phonegap
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'




  get  '/main/columns'
  get  '/main/import'
  get  '/main/foto'
  post '/main/do_import'
  post '/main/do_clear_all'
  get  '/lecturas/pendientes'
  post  '/update_lectura', to: 'lecturas#update_lectura'
  post  '/update_foto', to: 'lecturas#update_foto'
  get  '/main/test_update_lectura'
  get  '/lecturas/delete_foto', to: 'lecturas#delete_foto'
  match  '/lecturas/add_foto', to: 'lecturas#add_foto', via: [:get, :post, :put]

  post '/lecturas/update_lectura'
  match '/lecturas/filtrar', to: 'lecturas#filtrar', via: [:get, :post]
  match '/lecturas/:id/georeferenciar', to: 'lecturas#georeferenciar', via: 'post' 
  match '/lecturas/:id/visualizar', to: 'lecturas#visualizar', via: [:get, :post ]
  match '/lecturas/:id/mini', to: 'lecturas#mini', via: [:get, :post ]
  match '/lecturas/:id/fotos', to: 'lecturas#fotos', via: [:get, :post ]
  match '/lecturas/georeferenciar', to: 'lecturas#georeferenciar_lista', via: ['get','post'] 

  get  '/ruta/index'
  get  '/ruta/periodos'
  post '/ruta/asignar'
  post '/ruta/nuevo_periodo'
  match '/track', to: 'users#track', via: [:post, :get]
  match '/tracks', to: 'users#tracks', via: [:get]

  match '/direccion/:calle/:altura', to: 'main#direccion', via: [:get]
  match '/direcciones/:uh', to: 'main#direcciones', via: [:get]
  match '/buscar_direccion', to: 'main#buscar_direccion', via: 'get'
  post '/guardar_direccion', to: 'main#guardar_direccion'
  post '/agregar_direccion', to: 'main#agregar_direccion'
  resources :lecturas
  resources :lecturistas
  resources :incidencias
  resources :cities
  resources :users

  get "/qcode" => 'main#qcode'
  match "/upload", to: 'main#upload', via: [:get, :post]
  get "/download_mobile" => "main#download_mobile"
  get "/test_mail" => "main#test_mail"



  get "jobs/index"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]



end

app/models/edificio.rb
class Edificio < ActiveRecord::Base
end

app/controllers/edificios_controller.rb
class EdificiosController < ApplicationController
  before_action :set_edificio, only: [:show, :edit, :update, :destroy]

  # GET /edificios
  # GET /edificios.json
  def index
    @edificios = Edificio.all
  end

  # GET /edificios/1
  # GET /edificios/1.json
  def show
  end

  # GET /edificios/new
  def new
    @edificio = Edificio.new
  end

  # GET /edificios/1/edit
  def edit
  end

  # POST /edificios
  # POST /edificios.json
  def create
    @edificio = Edificio.new(edificio_params)

    respond_to do |format|
      if @edificio.save
        format.html { redirect_to @edificio, notice: 'Edificio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @edificio }
      else
        format.html { render action: 'new' }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edificios/1
  # PATCH/PUT /edificios/1.json
  def update
    respond_to do |format|
      if @edificio.update(edificio_params)
        format.html { redirect_to @edificio, notice: 'Edificio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edificios/1
  # DELETE /edificios/1.json
  def destroy
    @edificio.destroy
    respond_to do |format|
      format.html { redirect_to edificios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edificio
      @edificio = Edificio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edificio_params
      params.require(:edificio).permit(:calle, :altura, :cant_uh, :lat, :lon)
    end
end

app/helpers/edificios_helper.rb
module EdificiosHelper
end

app/views/edificios/_form.html.erb
<%= form_for(@edificio) do |f| %>
  <% if @edificio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edificio.errors.count, "error") %> prohibited this edificio from being saved:</h2>

      <ul>
      <% @edificio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calle %><br>
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :altura %><br>
    <%= f.number_field :altura %>
  </div>
  <div class="field">
    <%= f.label :cant_uh %><br>
    <%= f.number_field :cant_uh %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/edificios/edit.html.erb
<h1>Editing edificio</h1>

<%= render 'form' %>

<%= link_to 'Show', @edificio %> |
<%= link_to 'Back', edificios_path %>

app/views/edificios/index.html.erb
<h1>Listing edificios</h1>

<table>
  <thead>
    <tr>
      <th>Calle</th>
      <th>Altura</th>
      <th>Cant uh</th>
      <th>Lat</th>
      <th>Lon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @edificios.each do |edificio| %>
      <tr>
        <td><%= edificio.calle %></td>
        <td><%= edificio.altura %></td>
        <td><%= edificio.cant_uh %></td>
        <td><%= edificio.lat %></td>
        <td><%= edificio.lon %></td>
        <td><%= link_to 'Show', edificio %></td>
        <td><%= link_to 'Edit', edit_edificio_path(edificio) %></td>
        <td><%= link_to 'Destroy', edificio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edificio', new_edificio_path %>

app/views/edificios/new.html.erb
<h1>New edificio</h1>

<%= render 'form' %>

<%= link_to 'Back', edificios_path %>

app/views/edificios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calle:</strong>
  <%= @edificio.calle %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @edificio.altura %>
</p>

<p>
  <strong>Cant uh:</strong>
  <%= @edificio.cant_uh %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @edificio.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @edificio.lon %>
</p>

<%= link_to 'Edit', edit_edificio_path(@edificio) %> |
<%= link_to 'Back', edificios_path %>