config/routes.rb
FirstApp::Application.routes.draw do

  resources :edificios

  root 'main#home'

  # Autent... routes  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/login',  to: 'sessions#login',         via: 'post' #acceso por phonegap
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'




  get  '/main/columns'
  get  '/main/import'
  get  '/main/foto'
  post '/main/do_import'
  post '/main/do_clear_all'
  get  '/lecturas/pendientes'
  post  '/update_lectura', to: 'lecturas#update_lectura'
  post  '/update_foto', to: 'lecturas#update_foto'
  get  '/main/test_update_lectura'
  get  '/lecturas/delete_foto', to: 'lecturas#delete_foto'
  match  '/lecturas/add_foto', to: 'lecturas#add_foto', via: [:get, :post, :put]

  post '/lecturas/update_lectura'
  match '/lecturas/filtrar', to: 'lecturas#filtrar', via: [:get, :post]
  match '/lecturas/:id/georeferenciar', to: 'lecturas#georeferenciar', via: 'post' 
  match '/lecturas/:id/visualizar', to: 'lecturas#visualizar', via: [:get, :post ]
  match '/lecturas/:id/mini', to: 'lecturas#mini', via: [:get, :post ]
  match '/lecturas/:id/fotos', to: 'lecturas#fotos', via: [:get, :post ]
  match '/lecturas/georeferenciar', to: 'lecturas#georeferenciar_lista', via: ['get','post'] 

  get  '/ruta/index'
  get  '/ruta/periodos'
  post '/ruta/asignar'
  post '/ruta/nuevo_periodo'
  match '/track', to: 'users#track', via: [:post, :get]
  match '/tracks', to: 'users#tracks', via: [:get]

  match '/direccion/:calle/:altura', to: 'main#direccion', via: [:get]
  match '/direcciones/:uh', to: 'main#direcciones', via: [:get]
  match '/buscar_direccion', to: 'main#buscar_direccion', via: 'get'
  post '/guardar_direccion', to: 'main#guardar_direccion'
  post '/agregar_direccion', to: 'main#agregar_direccion'
  resources :lecturas
  resources :lecturistas
  resources :incidencias
  resources :cities
  resources :users

  get "/qcode" => 'main#qcode'
  match "/upload", to: 'main#upload', via: [:get, :post]
  get "/download_mobile" => "main#download_mobile"
  get "/test_mail" => "main#test_mail"



  get "jobs/index"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]



end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.name = name.downcase }
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  validates :password, length: { minimum: 6 }
  
  has_secure_password


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def to_s
    name
  end

  def send_mail
    UserMailer.welcome(self).deliver
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include SessionsHelper
    before_filter :signed_in_user

 before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :show]
 before_action :correct_user,   only: [:edit, :update]
 before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id]);
  end

  def preferences
    @user = current_user
    render :show
  end

  def track
    Track.create user: current_user, lat: params[:lat], lon: params[:lng], pos: params[:pos].to_s, device: params[:device].to_s
    render :json => {result: 'ok'}
  end

  def tracks

    @tracks = Track.search(params) 
    @user_cant = @tracks.group(:user).count #.merge( User.all.map{|u| [u , 0]} )
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      #UserMailer.welcome(@user).deliver
      redirect_to @user
    else
      render 'new'
    end
  end

  def editwrong_user
     @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      #UserMailer.welcome(@user).deliver
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

    private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      #redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :remember_token %><br>
    <%= f.text_field :remember_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_mapa_g.html.erb
<fieldset>
<legend onclick="$(this).next('div').slideToggle()">Mapa</legend>
<div>
		<div id="map" class="mapa"></div>
		<div class="text-right">
			<a onclick="map_fs('#map')" class="btn btn-primary">Pantalla completa</a>
		</div>
</div>
</fieldset>


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

<script type="text/javascript">

//$.getScript('https://maps.googleapis.com/maps/api/js?key=xxx&sensor=false');

function init() {
	points = [];
	<%  @tracks.select{|a| a.lat.present?}.each do |l| %>
	    points.push([ <%= l.lat %> , <%= l.lon %>]);
	<% end %>

  var mapOptions = {
    center: new google.maps.LatLng(points[0][0], points[0][1]),
    zoom: 14,
  }
  var map = new google.maps.Map(document.getElementById('map'), mapOptions);


	<%  @tracks.select{|a| a.lat.present?}.each do |l| %>	
	  new google.maps.Marker({
		  position: new google.maps.LatLng( <%= l.lat %> , <%= l.lon %> ),
		  map: map,
		  icon: '/images/red-dot.png',
	      title: '<%= l.user.name if l.user %>',
	  });
  	<% end %>		
		
	
		

}


google.maps.event.addDomListener(window, 'load', init);

</script>

cant: <%=@tracks.count%>

app/views/users/_mapa_ol3.html.erb
<h1>OL3</h1>




    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>

<div id="map" class="map"></div>

<script type="text/javascript">
osm = new ol.layer.Tile({ source: new ol.source.OSM() });
/*
google_layers =  [
            new OpenLayers.Layer.Google(
                "Google Physical",
                {type: google.maps.MapTypeId.TERRAIN}
            ),
            new OpenLayers.Layer.Google(
                "Google Streets", // the default
                {numZoomLevels: 20}
            ),
            new OpenLayers.Layer.Google(
                "Google Hybrid",
                {type: google.maps.MapTypeId.HYBRID, numZoomLevels: 20}
            ),
            new OpenLayers.Layer.Google(
                "Google Satellite",
                {type: google.maps.MapTypeId.SATELLITE, numZoomLevels: 22}
            )
        ];
*/

p = <%=raw a = @tracks.select{|a| a.present? && a.lat.present?}.first; a.nil? ? [-54,-34] :  [a.lon, a.lat] %>;

var map = new ol.Map({
  controls: ol.control.defaults().extend([
    new ol.control.FullScreen(),
  ]),
  target: 'map',
  layers: [osm],
  view: new ol.View2D({
    center: ol.proj.transform(p, 'EPSG:4326', 'EPSG:3857'),
    zoom: 16  
  })
});
            
<%  @tracks.select{|a| a.lat.present?}.each do |l| %>
      p = [ <%= l.lon %> , <%= l.lat %>];
      g = new ol.geom.Point( p ).transform('EPSG:4326', 'EPSG:3857');
      map.addOverlay(new ol.Overlay({
        position: ol.proj.transform(p, 'EPSG:4326', 'EPSG:3857'),
        element: $('<img src="/images/red-dot.png">')
            .css({marginTop: '-200%', marginLeft: '-50%', cursor: 'pointer'})
            .tooltip({title: '<%=raw l.marker_tooltip%>', trigger: 'hover'})
      }))
<% end %>



</script>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="col">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="field">
      <%= f.label :name %> <br/>
      <%= f.text_field :name %>
      </div>
      <div class="field">
      <%= f.label :email %> <br/>
      <%= f.text_field :email %>
      </div>
      <div class="field">
      <%= f.label :password %> <br/>
      <%= f.password_field :password %>
      </div>
      <div class="field">
      <%= f.label :password_confirmation, "Confirm Password" %> <br/>
      <%= f.password_field :password_confirmation %>
      </div>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
<br/><br/>


    <%= gravatar_for @user, 44 %>
    <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuarios') %>

<h1>Usuarios</h1>

<%= will_paginate %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

<br>

<%= link_to 'Nuevo Usuario', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="_row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for(@user, 44) %>
  <%= @user.name %>
</h1>
<h3>  <%= @user.email %>
  <%= @user.admin %>
</h3>

app/views/users/tracks.html.erb
<%= form_tag tracks_path, :method => 'get', :id => "tracks_search" do %>

    <%= label_tag "Desde" %>
    <%= select_tag 'desde', options_for_select([
      [" 2 hs", 2],
      [" 6 hs", 6],
      ["12 hs", 12],
      ["24 hs", 24],
      ["48 hs", 48],
      ["10 dias", 240],
      ["20 dias", 480],
      ["Todos", 99999999]
      ], params[:desde] || 48 ) %>

    <%= hidden_field_tag 'user' , params[:user], {id: 'h_user'} %>

    <%= submit_tag "Filtrar", {id: 'submit_btn', class: "btn btn-primary "} %>

<% end %>


<div class="row">
  <div class="col-md-2" style="padding-top: 90px">
    <ul class="nav nav-pills nav-stacked">
    <% @user_cant.each do |u,cant| %>
      <% if  params[:user].to_s == u.to_s %>
        <li class="active" >
      <% else %>
        <li  >
      <% end %>
        <a href="#" onclick="$('#h_user').val('<%=u%>'); $('#submit_btn').click()" ><span class="badge pull-right"><%=cant%></span><%= u.to_s  %>&nbsp;</a>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="col-md-10">
	<%= render 'mapa_ol3' %>
  </div>
</div>