config/routes.rb
FirstApp::Application.routes.draw do

  resources :edificios

  root 'main#home'

  # Autent... routes  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/login',  to: 'sessions#login',         via: 'post' #acceso por phonegap
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'




  get  '/main/columns'
  get  '/main/import'
  get  '/main/foto'
  post '/main/do_import'
  post '/main/do_clear_all'
  get  '/lecturas/pendientes'
  post  '/update_lectura', to: 'lecturas#update_lectura'
  post  '/update_foto', to: 'lecturas#update_foto'
  get  '/main/test_update_lectura'
  get  '/lecturas/delete_foto', to: 'lecturas#delete_foto'
  match  '/lecturas/add_foto', to: 'lecturas#add_foto', via: [:get, :post, :put]

  post '/lecturas/update_lectura'
  match '/lecturas/filtrar', to: 'lecturas#filtrar', via: [:get, :post]
  match '/lecturas/:id/georeferenciar', to: 'lecturas#georeferenciar', via: 'post' 
  match '/lecturas/:id/visualizar', to: 'lecturas#visualizar', via: [:get, :post ]
  match '/lecturas/:id/mini', to: 'lecturas#mini', via: [:get, :post ]
  match '/lecturas/:id/fotos', to: 'lecturas#fotos', via: [:get, :post ]
  match '/lecturas/georeferenciar', to: 'lecturas#georeferenciar_lista', via: ['get','post'] 

  get  '/ruta/index'
  get  '/ruta/periodos'
  post '/ruta/asignar'
  post '/ruta/nuevo_periodo'
  match '/track', to: 'users#track', via: [:post, :get]
  match '/tracks', to: 'users#tracks', via: [:get]

  match '/direccion/:calle/:altura', to: 'main#direccion', via: [:get]
  match '/direcciones/:uh', to: 'main#direcciones', via: [:get]
  match '/buscar_direccion', to: 'main#buscar_direccion', via: 'get'
  post '/guardar_direccion', to: 'main#guardar_direccion'
  post '/agregar_direccion', to: 'main#agregar_direccion'
  resources :lecturas
  resources :lecturistas
  resources :incidencias
  resources :cities
  resources :users

  get "/qcode" => 'main#qcode'
  match "/upload", to: 'main#upload', via: [:get, :post]
  get "/download_mobile" => "main#download_mobile"
  get "/test_mail" => "main#test_mail"



  get "jobs/index"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]



end

app/models/incidencia.rb
class Incidencia < ActiveRecord::Base
	validate :nombre, uniqueness: true
end

app/controllers/incidencias_controller.rb
class IncidenciasController < ApplicationController
    include SessionsHelper
    before_filter :signed_in_user

  before_action :set_incidencia, only: [:show, :edit, :update, :destroy]

  # GET /incidencias
  # GET /incidencias.json
  def index
    @incidencias = Incidencia.all
  end

  # GET /incidencias/1
  # GET /incidencias/1.json
  def show
  end

  # GET /incidencias/new
  def new
    @incidencia = Incidencia.new
  end

  # GET /incidencias/1/edit
  def edit
  end

  # POST /incidencias
  # POST /incidencias.json
  def create
    @incidencia = Incidencia.new(incidencia_params)

    respond_to do |format|
      if @incidencia.save
        format.html { redirect_to @incidencia, notice: 'Incidencia was successfully created.' }
        format.json { render action: 'show', status: :created, location: @incidencia }
      else
        format.html { render action: 'new' }
        format.json { render json: @incidencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidencias/1
  # PATCH/PUT /incidencias/1.json
  def update
    respond_to do |format|
      if @incidencia.update(incidencia_params)
        format.html { redirect_to @incidencia, notice: 'Incidencia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @incidencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidencias/1
  # DELETE /incidencias/1.json
  def destroy
    @incidencia.destroy
    respond_to do |format|
      format.html { redirect_to incidencias_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incidencia
      @incidencia = Incidencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incidencia_params
      params.require(:incidencia).permit(:nombre, :requiere_lectura, :dato_requerido, :dato_rexp, :incidencias_incompatibles, :tipo)
    end
end

app/helpers/incidencias_helper.rb
module IncidenciasHelper
end

app/views/incidencias/_form.html.erb
<%= form_for(@incidencia) do |f| %>
  <% if @incidencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incidencia.errors.count, "error") %> prohibited this incidencia from being saved:</h2>

      <ul>
      <% @incidencia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :requiere_lectura %><br>
    <%= f.text_field :requiere_lectura %>
  </div>
  <div class="field">
    <%= f.label :dato_requerido %><br>
    <%= f.text_field :dato_requerido %>
  </div>
  <div class="field">
    <%= f.label :dato_rexp %><br>
    <%= f.text_field :dato_rexp %>
  </div>
  <div class="field">
    <%= f.label :incidencias_incompatibles %><br>
    <%= f.text_field :incidencias_incompatibles %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidencias/edit.html.erb
<h1>Editing incidencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @incidencia %> |
<%= link_to 'Back', incidencias_path %>

app/views/incidencias/index.html.erb
<h1>Listing incidencias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Requiere lectura</th>
      <th>Dato requerido</th>
      <th>Dato rexp</th>
      <th>Incidencias incompatibles</th>
      <th>Tipo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @incidencias.each do |incidencia| %>
      <tr>
        <td><%= incidencia.nombre %></td>
        <td><%= incidencia.requiere_lectura %></td>
        <td><%= incidencia.dato_requerido %></td>
        <td><%= incidencia.dato_rexp %></td>
        <td><%= incidencia.incidencias_incompatibles %></td>
        <td><%= incidencia.tipo %></td>
        <td><%= link_to 'Show', incidencia %></td>
        <td><%= link_to 'Edit', edit_incidencia_path(incidencia) %></td>
        <td><%= link_to 'Destroy', incidencia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incidencia', new_incidencia_path %>

app/views/incidencias/new.html.erb
<h1>New incidencia</h1>

<%= render 'form' %>

<%= link_to 'Back', incidencias_path %>

app/views/incidencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @incidencia.nombre %>
</p>

<p>
  <strong>Requiere lectura:</strong>
  <%= @incidencia.requiere_lectura %>
</p>

<p>
  <strong>Dato requerido:</strong>
  <%= @incidencia.dato_requerido %>
</p>

<p>
  <strong>Dato rexp:</strong>
  <%= @incidencia.dato_rexp %>
</p>

<p>
  <strong>Incidencias incompatibles:</strong>
  <%= @incidencia.incidencias_incompatibles %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @incidencia.tipo %>
</p>

<%= link_to 'Edit', edit_incidencia_path(@incidencia) %> |
<%= link_to 'Back', incidencias_path %>