config/routes.rb
FirstApp::Application.routes.draw do

  resources :edificios

  root 'main#home'

  # Autent... routes  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/login',  to: 'sessions#login',         via: 'post' #acceso por phonegap
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/preferences', to: 'users#preferences', via: 'get'




  get  '/main/columns'
  get  '/main/import'
  get  '/main/foto'
  post '/main/do_import'
  post '/main/do_clear_all'
  get  '/lecturas/pendientes'
  post  '/update_lectura', to: 'lecturas#update_lectura'
  post  '/update_foto', to: 'lecturas#update_foto'
  get  '/main/test_update_lectura'
  get  '/lecturas/delete_foto', to: 'lecturas#delete_foto'
  match  '/lecturas/add_foto', to: 'lecturas#add_foto', via: [:get, :post, :put]

  post '/lecturas/update_lectura'
  match '/lecturas/filtrar', to: 'lecturas#filtrar', via: [:get, :post]
  match '/lecturas/:id/georeferenciar', to: 'lecturas#georeferenciar', via: 'post' 
  match '/lecturas/:id/visualizar', to: 'lecturas#visualizar', via: [:get, :post ]
  match '/lecturas/:id/mini', to: 'lecturas#mini', via: [:get, :post ]
  match '/lecturas/:id/fotos', to: 'lecturas#fotos', via: [:get, :post ]
  match '/lecturas/georeferenciar', to: 'lecturas#georeferenciar_lista', via: ['get','post'] 

  get  '/ruta/index'
  get  '/ruta/periodos'
  post '/ruta/asignar'
  post '/ruta/nuevo_periodo'
  match '/track', to: 'users#track', via: [:post, :get]
  match '/tracks', to: 'users#tracks', via: [:get]

  match '/direccion/:calle/:altura', to: 'main#direccion', via: [:get]
  match '/direcciones/:uh', to: 'main#direcciones', via: [:get]
  match '/buscar_direccion', to: 'main#buscar_direccion', via: 'get'
  post '/guardar_direccion', to: 'main#guardar_direccion'
  post '/agregar_direccion', to: 'main#agregar_direccion'
  resources :lecturas
  resources :lecturistas
  resources :incidencias
  resources :cities
  resources :users

  get "/qcode" => 'main#qcode'
  match "/upload", to: 'main#upload', via: [:get, :post]
  get "/download_mobile" => "main#download_mobile"
  get "/test_mail" => "main#test_mail"



  get "jobs/index"
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]



end

app/models/lecturista.rb
class Lecturista < ActiveRecord::Base
	validates :nombre, uniqueness: true
end

app/controllers/lecturistas_controller.rb
class LecturistasController < ApplicationController
  include SessionsHelper
  before_filter :signed_in_user

  before_action :set_lecturista, only: [:show, :edit, :update, :destroy]

  # GET /lecturistas
  # GET /lecturistas.json
  def index
    @lecturistas = Lecturista.all
  end

  # GET /lecturistas/1
  # GET /lecturistas/1.json
  def show
  end

  # GET /lecturistas/new
  def new
    @lecturista = Lecturista.new
  end

  # GET /lecturistas/1/edit
  def edit
  end

  # POST /lecturistas
  # POST /lecturistas.json
  def create
    @lecturista = Lecturista.new(lecturista_params)

    respond_to do |format|
      if @lecturista.save
        format.html { redirect_to @lecturista, notice: 'Lecturista was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lecturista }
      else
        format.html { render action: 'new' }
        format.json { render json: @lecturista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lecturistas/1
  # PATCH/PUT /lecturistas/1.json
  def update
    respond_to do |format|
      if @lecturista.update(lecturista_params)
        format.html { redirect_to @lecturista, notice: 'Lecturista was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lecturista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lecturistas/1
  # DELETE /lecturistas/1.json
  def destroy
    @lecturista.destroy
    respond_to do |format|
      format.html { redirect_to lecturistas_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_lecturista
    @lecturista = Lecturista.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lecturista_params
    params.require(:lecturista).permit(:nombre)
  end
  

end

app/helpers/lecturistas_helper.rb
module LecturistasHelper
end

app/views/lecturistas/_form.html.erb
<%= form_for(@lecturista) do |f| %>
  <% if @lecturista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecturista.errors.count, "error") %> prohibited this lecturista from being saved:</h2>

      <ul>
      <% @lecturista.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lecturistas/edit.html.erb
<h1>Editing lecturista</h1>

<%= render 'form' %>

<%= link_to 'Ver', @lecturista %> |
<%= link_to 'Volver', lecturistas_path %>

app/views/lecturistas/index.html.erb
<h1>Lecturistas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lecturistas.each do |lecturista| %>
      <tr>
        <td><%= lecturista.nombre %></td>
        <td><%= link_to 'Ver', lecturista %></td>
        <td><%= link_to 'Editar', edit_lecturista_path(lecturista) %></td>
        <td><%= link_to 'Eliminar', lecturista, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Lecturista', new_lecturista_path %>

app/views/lecturistas/new.html.erb
<h1>New lecturista</h1>

<%= render 'form' %>

<%= link_to 'Back', lecturistas_path %>

app/views/lecturistas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @lecturista.nombre %>
</p>

<%= link_to 'Edit', edit_lecturista_path(@lecturista) %> |
<%= link_to 'Back', lecturistas_path %>